steps:
# Git checkout
#- name: 'gcr.io/cloud-builders/git'
#  args: ['checkout', 'master']
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config --global credential.helper '!gcloud auth application-default print-access-token | git credential-gcloud.sh'
      git clone https://iammageshs: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@github.com/iammageshs/cloud-build.git


# Maven build
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth activate-service-account --key-file=/home/ubuntu/grafana-monitoring-demo-9af85f3c62a5.json
      gcloud compute ssh --project=grafana-monitoring-demo --zone=asia-south1-a demo --command="cd /home/ubuntu/build/adaptor/beckn-gateway/beckn-common & mvn clean install"

