steps:
# Git checkout
#- name: 'gcr.io/cloud-builders/git'
#  args: ['checkout', 'master']
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git clone https://github.com/devopsguyz/ondc-test.git

# Maven build
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth activate-service-account --key-file=/home/ubuntu/grafana-monitoring-demo-9af85f3c62a5.json
      gcloud compute ssh --project=grafana-monitoring-demo --zone=asia-south1-a demo --command="cd /home/ubuntu/build/adaptor/beckn-gateway/beckn-common & mvn clean install"

