steps:
# Git checkout
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'master']

# Maven build
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth activate-service-account --key-file=/home/ubuntu/grafana-monitoring-demo-9af85f3c62a5.json
      gcloud compute ssh --project=grafana-monitoring-demo --zone=asia-south1-a demo --command="cd /path/to/app && mvn clean install"

